# Используем базовый образ Python
FROM python:3.9-slim-bullseye

# Создаем и переходим в рабочую директорию
WORKDIR /app

# Копируем файлы проекта в рабочую директорию
COPY requirements.txt .
COPY tg_bot.py .


COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Устанавливаем зависимости Python
RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p /app/logs
RUN apt-get update && \
    apt-get install -y openssh-server
# Запускаем скрипты через supervisord
CMD ["/usr/local/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

